name: Publish to npm

on:
  push:
    tags:
      - "v*"

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: "https://registry.npmjs.org"
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Install
        run: npm ci

      - name: Verify
        run: npm run verify

      - name: Dry-run packages
        run: npm run pack:dry-run

      # - name: Publish @blcklab/porma
      #   working-directory: packages/porma
      #   run: npm publish --access public --tag rc
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      # - name: Publish @blcklab/porma-compiler
      #   working-directory: packages/porma-compiler
      #   run: npm publish --access public --tag rc
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      # - name: Publish @blcklab/porma-vite
      #   working-directory: packages/porma-vite
      #   run: npm publish --access public --tag rc
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      # - name: Publish @blcklab/porma-router
      #   working-directory: packages/porma-router
      #   run: npm publish --access public --tag rc
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish create-porma
        working-directory: packages/create-porma
        run: npm publish --access public --tag rc
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}